# Site settings
# in the templates available like {{ site.myvariable }}.
title: LOVE
email: wangshaokang2008@domain.com
brand: LOVE_DAILY
headline: every day, every hour, every minute and every second.
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2018 LOVE Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: wangshaokang2008@126.com
phone: 777777777777

# Tracking
googleAnalitycsID: UA-83933844-1

